[package]
name = "OpenBattlesimGen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "1.4.19", features = ["fltk-bundled"] }
libnoise = {version = "1.0.0", features = ["image"]}
rand = "0.8.5"

[build-dependencies]
fl2rust = "0.5.17"
